# NumPy Exercise: Creating a 4x4 ndarray of Even Numbers

## Overview

This short exercise explores how to create and reshape NumPy arrays efficiently.  
The goal is to generate a 4x4 matrix containing even numbers between 2 and 32 using NumPy’s built-in functions.

Working with arrays is an essential skill in data analysis and scientific computing, as they provide the foundation for handling large datasets and performing vectorized computations.

In [1]:
import numpy as np

# Create a NumPy array containing even numbers from 2 to 32
# np.arange() generates evenly spaced values within a given interval.
# The reshape() method organizes the sequence into a 4x4 matrix.

X = np.arange(2, 34, 2).reshape(4, 4)

# Display the resulting array
print("4x4 ndarray of even numbers:")
print(X)

4x4 ndarray of even numbers:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


## Output Explanation

The result is a 4x4 ndarray structured as follows:
4x4 ndarray of even numbers:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

## Reflection

This exercise reinforces how array creation and reshaping can simplify working with numeric data.  
In future exercises, similar techniques will be used to explore slicing, indexing, and mathematical operations — forming the base for more advanced data analysis tasks.