## 🧮 Manipulating ndarrays with NumPy

**Objective:**  
Create and manipulate NumPy arrays to practice Boolean indexing, array reshaping, and data inspection.  

This exercise focuses on generating a 5×5 array of integers from 1 to 25 and extracting only the odd numbers using Boolean masking.

In [2]:
import numpy as np

# --- Array Creation ---
# Create a 5x5 ndarray with consecutive integers from 1 to 25 (inclusive)
X = np.arange(1, 26).reshape(5, 5)

# --- Array Manipulation ---
# Use Boolean indexing to extract only odd numbers
odd_mask = X % 2 != 0
Y = X[odd_mask]

# --- Optional Verification & Insights ---
# Verify shape, dtype, and array properties
print("📊 Original 5x5 Array (X):\n", X)
print("\n✅ Array Shape:", X.shape)
print("✅ Data Type:", X.dtype)

print("\n🔍 Boolean Mask for Odd Numbers:\n", odd_mask.astype(int))
print("\n🎯 Extracted Odd Numbers (Y):\n", Y)
print("✅ Total Odd Numbers Extracted:", Y.size)

# --- Advanced Manipulation (Optional Learning Section) ---
# Reshape Y into a 3x? matrix (padding not needed here since Y has 13 elements)
# Example: You could reshape or view as 1-D, or even normalize, etc.
Y_flat = Y.flatten()
print("\n📈 Flattened View of Odd Numbers:\n", Y_flat)


📊 Original 5x5 Array (X):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

✅ Array Shape: (5, 5)
✅ Data Type: int64

🔍 Boolean Mask for Odd Numbers:
 [[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

🎯 Extracted Odd Numbers (Y):
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]
✅ Total Odd Numbers Extracted: 13

📈 Flattened View of Odd Numbers:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


### 🧠 Reflection
From this exercise, I learned:
- How to create structured arrays using `np.arange()` and `reshape()`.  
- How Boolean masks can filter arrays based on custom conditions.  
- How to inspect arrays using `.shape`, `.dtype`, and `.size`.  
- The value of flattening and viewing data in different dimensions.  